run:
  timeout: 5m
  tests: false

linters:
  enable-all: true
  disable:
    - unused # The repository has no Application Life Cycle Management. Run manually prior to a release.
    - deadcode # The repository has no Application Life Cycle Management. Run manually prior to a release.
    - gomnd # Run manually prior to a release.
    - gomoddirectives # The repository uses go modules in its interpreter functionality from a temporary tagged fork.

    - gocognit # temporary prior to new matcher implementation
    - goerr113 # temporary prior to new release
    - errorlint # enable

    - lll
    - nlreturn
    - whitespace
    - wsl
    - forbidigo
    - gochecknoglobals # No data race conditions
    - gofumpt # too many false positives
    - exhaustivestruct # exhausting
    - varnamelen # for loops
    - cyclop # can't handle switch statement
    - funlen # can't handle switch statement


    - golint # deprecated
    - scopelint # deprecated
    - interfacer # deprecated
    - maligned # deprecated

  fast: false
linters-settings:
  govet:
    enable-all: true
    disable:
      - shadow
      # - fieldalignment