run:
  timeout: 5m
  tests: false

linters:
  enable-all: true
  disable:
    - unused # The repository has no Application Life Cycle Management. Run manually prior to a release.
    - deadcode # The repository has no Application Life Cycle Management. Run manually prior to a release.
    - gomoddirectives # The repository uses go modules in its interpreter functionality from a temporary tagged fork.

    - varnamelen # temporary prior to new parser implementation
    - cyclop # temporary prior to new parser implementation
    - gocognit # temporary prior to new parser implementation

    - wrapcheck # enable
    - goerr113 # enable
    - errorlint # enable
    - exhaustivestruct # enable
    - gomnd # enable
    - forcetypeassert # enable

    - lll
    - nlreturn
    - whitespace
    - wsl
    - forbidigo

    - golint # deprecated
    - scopelint # deprecated
    - interfacer # deprecated
    - maligned # deprecated

  fast: false
linters-settings:
  govet:
    enable-all: true
    disable:
      - shadow
      # - fieldalignment

  funlen:
    lines: 80