name: Integration Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  Integration:
    name: test

    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Run tests
        run: go test ./examples/_tests
